"""Write the independent-review bundle for the Verify study.

    python validation/verify-study/review_bundle.py            # write REVIEW_BUNDLE.md
    python validation/verify-study/review_bundle.py --check    # fail if it is stale

The bundle lists the cases most worth a second, independent reading before
release, each with exactly what changed, the judgement recorded before Verify
ran, and what Verify said:

- every case judged to change protected meaning;
- every ACCEPTED case whose acceptance rests on a move or an equivalence,
  including PlainSpeak's own SAFE rules — field report FIELD-001 showed a SAFE
  rule can be wrong;
- the two probes that were false acceptances under verification policy 2026.1.

It changes nothing in the study. It exists so a person who did not write the
cases can check the judgements and the results without running anything.
"""
from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import run_study  # noqa: E402

BUNDLE = HERE / "REVIEW_BUNDLE.md"
HISTORICAL = ("X02", "X04")
TOKEN = re.compile(r"\S+")


def changes(before: str, after: str, limit: int = 12) -> list[str]:
    """The changed stretches, a few words of context each side."""
    a, b = TOKEN.findall(before), TOKEN.findall(after)
    hunks = []
    for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, a, b, autojunk=False).get_opcodes():
        if tag == "equal":
            continue
        lead = " ".join(a[max(0, i1 - 3):i1])
        trail = " ".join(a[i2:i2 + 3])
        old = " ".join(a[i1:i2]) or "∅"
        new = " ".join(b[j1:j2]) or "∅"
        hunks.append(f"…{lead} **[{old} → {new}]** {trail}…".replace("|", "\\|"))
    if len(hunks) > limit:
        hunks = hunks[:limit] + [f"… and {len(hunks) - limit} more change(s)"]
    return hunks or ["(no textual change)"]


def render() -> str:
    cases = {case["id"]: case for case in run_study.cases()}
    results = json.loads((HERE / "results.json").read_text(encoding="utf-8"))

    def entry(key: str) -> list[str]:
        case, result = cases[key], results[key]
        findings = result["refused"] or result["unresolved"] or result["accounted_for"]
        lines = [
            f"### {key} — {result['class']} — Verify: **{result['result']}**",
            "",
            f"- Judged: meaning **{result['meaning']}**"
            + (", protected meaning" if result["protected"] else "") + f" — {result['note']}",
            f"- Source: `{result['source']}`; producer: {case['producer']}",
            f"- Verify's findings: {', '.join(findings) or 'none'}",
            "- What changed:",
        ]
        lines += [f"  - {hunk}" for hunk in changes(case["before_text"], case["after_text"])]
        lines.append("")
        return lines

    protected = sorted(key for key, value in results.items() if value["protected"])
    moved_or_equivalent = sorted(
        key for key, value in results.items()
        if value["result"] == "ACCEPTED"
        and {"permitted_move", "fact_equivalence"} & set(value["accounted_for"])
    )
    safe_rules = sorted(
        key for key, value in results.items()
        if value["result"] == "ACCEPTED" and "safe_rule" in value["accounted_for"]
        and key not in moved_or_equivalent
    )
    out = [
        "# Verify study: independent review bundle",
        "",
        "Generated by `validation/verify-study/review_bundle.py` from `cases.yaml` and",
        "`results.json`; do not edit by hand. Every judgement below was written before",
        "Verify ran and has not been changed since. A reviewer checks two things for",
        "each case: that the judgement is right, and that Verify's result is acceptable",
        "given it. **An ACCEPTED result on a case whose meaning changed is a release",
        "blocker.**",
        "",
        f"- Cases judged to change protected meaning: {len(protected)}",
        f"- ACCEPTED cases resting on a move or a fact equivalence: {len(moved_or_equivalent)}",
        f"- ACCEPTED cases resting on PlainSpeak's SAFE rules: {len(safe_rules)}",
        f"- Historical false-acceptance probes: {len(HISTORICAL)}",
        "",
        "## 1. The historical false acceptances",
        "",
        "Both were ACCEPTED under verification policy 2026.1 and are INCONCLUSIVE",
        "under 2026.2. See VERIFY_STUDY.md.",
        "",
    ]
    for key in HISTORICAL:
        out += entry(key)
    out += ["## 2. ACCEPTED on the strength of a move or an equivalence", ""]
    for key in moved_or_equivalent:
        out += entry(key)
    out += ["## 3. ACCEPTED on the strength of PlainSpeak's SAFE rules", "",
            "Each substitution below was accepted because it is one of PlainSpeak's",
            "reviewed SAFE rules. Field testing of 1.0.0 found one such rule wrong",
            "(FIELD-001, facilitate → help) and 27 more like it, all now diagnostics; a",
            "reviewer should read each remaining substitution in its sentence.", ""]
    for key in safe_rules:
        out += entry(key)
    out += ["## 4. Every case judged to change protected meaning", "",
            "None may be ACCEPTED. REFUSED says a protected item changed; INCONCLUSIVE says",
            "the model could not establish that it did not.", ""]
    for key in protected:
        if key not in HISTORICAL:
            out += entry(key)
    return "\n".join(out).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    rendered = render()
    if options.check:
        if not BUNDLE.exists() or BUNDLE.read_bytes().decode("utf-8") != rendered:
            print("REVIEW_BUNDLE.md is stale", file=sys.stderr)
            return 1
        return 0
    with open(BUNDLE, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(rendered)
    print(f"wrote {BUNDLE.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
