"""
Plain-language glossary mapping complex or jargon terms to simpler alternatives.

This glossary is curated from public plain-language resources including:
- Plain Language Action and Information Network (PLAIN) guidelines
- CDC Clear Communication Index
- UK Government Digital Service style guide
- Plain English Campaign resources

The mappings are suggestions, not rules. Domain-specific precision may
require keeping a term that has a simpler alternative listed here.
"""

# Each entry maps a jargon term/phrase to (simpler_alternative, explanation)
# The explanation helps users understand *why* the alternative might be better.
GLOSSARY: dict[str, tuple[str, str]] = {
    # --- Bureaucratic / official terms ---
    "accordingly": ("so", "A shorter, more direct word."),
    "additional": ("more", "Most readers prefer shorter words."),
    "additionally": ("also", "One word instead of four."),
    "adjacent to": ("next to", "Everyday language is clearer."),
    "advantageous": ("helpful", "Avoid Latin-derived words when a simpler one exists."),
    "afford an opportunity": ("allow", "Three words can become one."),
    "aforementioned": ("this", "Archaic language creates distance from the reader."),
    "aggregate": ("total", "Use common words your readers know."),
    "ameliorate": ("improve", "Plain words are understood by more people."),
    "antecedent to": ("before", "Prefer Anglo-Saxon to Latin-derived words."),
    "apparent": ("clear", "Shorter words reduce reading effort."),
    "approximately": ("about", "Precision is rarely lost with 'about'."),
    "as a consequence of": ("because of", "One word often replaces several."),
    "as a means of": ("to", "The simplest connecting word."),
    "as of the date of": ("from", "Cut unnecessary words."),
    "as prescribed by": ("under", "A single preposition works."),
    "as regards": ("about", "Modern, conversational words connect better."),
    "ascertain": ("find out", "Phrasal verbs are often clearer than Latinate ones."),
    "assistance": ("help", "The shorter word means the same thing."),
    "at the present time": ("now", "One syllable instead of five."),
    "attain": ("reach", "A common, everyday verb."),
    "attempt": ("try", "Shorter and more direct."),
    "by means of": ("by", "Unnecessary words add cognitive load."),
    "cease": ("stop", "Anglo-Saxon words are usually shorter."),
    "cognizant of": ("aware of", "A more commonly used word."),
    "commence": ("start", "One of the most common plain-language substitutions."),
    "commensurate with": ("in line with", "Avoid formal, legalistic phrasing."),
    "compensate": ("pay", "Directness builds trust."),
    "comply with": ("follow", "Phrasal verbs are more conversational."),
    "component": ("part", "Shorter words reduce reading grade level."),
    "concerning": ("about", "The simpler preposition."),
    "concerning the matter of": ("about", "Seven words can become one."),
    "consequently": ("so", "Connect ideas simply."),
    "consolidate": ("combine", "Use words your readers use every day."),
    "constitute": ("make up", "Phrasal verbs are friendlier."),
    "construct": ("build", "Concrete words are easier to picture."),
    "demonstrate": ("show", "The most direct verb for the meaning."),
    "designate": ("choose", "A word everyone knows."),
    "determine": ("decide", "Decision words should be clear."),
    "discontinue": ("stop", "Negative prefixes add decoding work."),
    "disseminate": ("share", "A common, everyday word."),
    "due to the fact that": ("because", "Five words become one."),
    "during the time that": ("while", "Simpler conjunction."),
    "echelons": ("levels", "Avoid military or bureaucratic jargon."),
    "effectuate": ("carry out", "A verb people actually say."),
    "elect": ("choose", "Shorter is clearer."),
    "elucidate": ("explain", "Use words readers can pronounce easily."),
    "employ": ("use", "'Employ' means hire; 'use' is the intended meaning."),
    "endeavor": ("try", "A stilted word with a simple equivalent."),
    "enumerate": ("list", "Concrete verbs help readers visualize."),
    "equivalent": ("equal", "Shorter adjective."),
    "establish": ("set up", "Phrasal verbs are more natural."),
    "evince": ("show", "An obscure word — replace with a common one."),
    "exacerbate": ("worsen", "Medical/bureaucratic term with a plainer alternative."),
    "exclusive of": ("except", "Simpler and clearer."),
    "exhibit": ("show", "As above — prefer the everyday verb."),
    "expedite": ("speed up", "A phrasal verb is less formal."),
    "expend": ("spend", "Shorter word, same meaning."),
    "expiration": ("end", "The concept in plain language."),
    "facilitate": ("help", "One of the most commonly overused formal words."),
    "finalize": ("finish", "'Finalize' is bureaucratic jargon."),
    "for the purpose of": ("to", "Four words to one."),
    "for the reason that": ("because", "Cut filler words."),
    "formulate": ("create", "A simpler word for making something."),
    "forthwith": ("now", "Archaic and formal."),
    "frequently": ("often", "Two syllables instead of three."),
    "functionality": ("feature", "Avoid '-ality' abstractions."),
    "furnish": ("give", "Everyday language."),
    "hereafter": ("from now on", "A phrase that is easier to parse."),
    "hereby": ("by this", "Legal archaism — modernize."),
    "herein": ("in this", "Another legal archaism."),
    "heretofore": ("until now", "Archaic and confusing."),
    "however": ("but", "When joining clauses, 'but' is shorter."),
    "identical": ("same", "Shorter word, same meaning."),
    "implement": ("carry out", "A phrasal verb is less abstract."),
    "in accordance with": ("under", "Simpler preposition."),
    "in addition to": ("and", "Coordinating conjunction is simpler."),
    "in advance of": ("before", "Cut unnecessary words."),
    "in an effort to": ("to", "Three words to one."),
    "in close proximity to": ("near", "Overwritten preposition."),
    "in conjunction with": ("with", "Simpler."),
    "in excess of": ("more than", "Less formal, equally precise."),
    "in lieu of": ("instead of", "Avoid French-derived legal phrases."),
    "in order to": ("to", "Three words to one — a classic cut."),
    "in receipt of": ("received", "Passive and wordy — use active voice."),
    "in regard to": ("about", "Simpler."),
    "in relation to": ("about", "Three words to one."),
    "in the absence of": ("without", "Simpler preposition."),
    "in the amount of": ("for", "Unnecessary wordiness."),
    "in the context of": ("in", "Cut filler phrases."),
    "in the course of": ("during", "Simpler."),
    "in the event of": ("if", "Conditional words should be short."),
    "in the near future": ("soon", "One word instead of five."),
    "in the process of": ("being", "Wordy construction."),
    "in view of the fact that": ("because", "Many words for one idea."),
    "inception": ("start", "A Latinate word with a plain equivalent."),
    "indicate": ("show", "Direct and simple."),
    "individual": ("person", "Use the concrete noun."),
    "initiate": ("start", "Another Latinate-start word."),
    "is applicable to": ("applies to", "Active phrasing."),
    "is authorized to": ("may", "Modal verb is simpler."),
    "is dependent upon": ("depends on", "Remove 'is' + adjective construction."),
    "is desirous of": ("wants", "Stilted — use the normal verb."),
    "is in a position to": ("can", "Modal verbs replace long phrases."),
    "is of the opinion that": ("believes", "Attribute the belief directly."),
    "it is essential that": ("must", "Cut dummy subject 'it'."),
    "it is imperative that": ("must", "Even stronger — but same simplification."),
    "it is probable that": ("probably", "Adverb is simpler than clause."),
    "liaise": ("work with", "Jargon — use everyday language."),
    "magnitude": ("size", "A simpler measurement word."),
    "maintain": ("keep", "Shorter, more common word."),
    "make a determination": ("decide", "Noun-heavy phrase -> verb."),
    "make a payment": ("pay", "Hidden verb behind a noun."),
    "make an application": ("apply", "Another hidden verb."),
    "make an effort": ("try", "Hidden verb."),
    "make reference to": ("refer to", "Hidden verb."),
    "materialize": ("happen", "Abstract -> concrete."),
    "methodology": ("method", "The '-ology' is usually unnecessary."),
    "modification": ("change", "Shorter noun form."),
    "modify": ("change", "Plain verb."),
    "necessitate": ("require", "A more common word."),
    "nevertheless": ("but", "Shorter connector."),
    "notify": ("tell", "The most direct communication verb."),
    "notwithstanding": ("despite", "A simpler preposition."),
    "numerous": ("many", "Fewer syllables."),
    "objective": ("goal", "Concrete nouns are clearer."),
    "obligated": ("must", "Modal verb is more direct."),
    "obtain": ("get", "The simplest verb of acquisition."),
    "occurrence": ("event", "Less abstract."),
    "on a daily basis": ("daily", "One word instead of five."),
    "on the grounds that": ("because", "Simpler."),
    "operational": ("working", "Everyday adjective."),
    "optimum": ("best", "Avoid superlative jargon."),
    "parameters": ("limits", "Use concrete nouns."),
    "participate": ("take part", "Phrasal verb."),
    "per annum": ("a year", "English instead of Latin."),
    "perform": ("do", "Direct verb."),
    "permissible": ("allowed", "Easier to understand."),
    "permit": ("let", "A common, short verb."),
    "personnel": ("staff", "A more specific, human word."),
    "pertaining to": ("about", "Simpler preposition."),
    "portion": ("part", "Shorter word."),
    "possess": ("have", "Ownership verb — keep simple."),
    "preceding": ("before", "Common word."),
    "predicated on": ("based on", "Simpler phrasing."),
    "preliminary": ("first", "Ordinal is clearer."),
    "prescribe": ("set", "For rules — use the direct verb."),
    "preserve": ("keep", "Shorter."),
    "previously": ("before", "Time words should be simple."),
    "prior to": ("before", "Two words to one."),
    "proceed": ("go ahead", "Phrasal verb."),
    "procure": ("get", "Simple acquisition verb."),
    "promulgate": ("announce", "An obscure word."),
    "provide": ("give", "Direct."),
    "provided that": ("if", "Conditional."),
    "provisions": ("rules", "Legal jargon -> plain word."),
    "purchase": ("buy", "The word people actually say."),
    "pursuant to": ("under", "Legal archaism."),
    "regarding": ("about", "Simpler preposition."),
    "relating to": ("about", "Simpler."),
    "remainder": ("rest", "Shorter."),
    "remit": ("send", "For payments — use the direct verb."),
    "remuneration": ("pay", "Jargon for wages."),
    "render": ("make", "A verb with many meanings — be specific."),
    "request": ("ask", "Direct communication."),
    "require": ("need", "A more human word."),
    "reside": ("live", "For residence — use the common word."),
    "retain": ("keep", "Shorter."),
    "revenue": ("income", "A more common word in some contexts."),
    "revision": ("change", "Plain noun."),
    "said": ("the", "Legal reference word — replace."),
    "selection": ("choice", "Shorter."),
    "shall": ("must", "Legal 'shall' is ambiguous — use 'must' for obligation."),
    "should it appear that": ("if", "Simpler conditional."),
    "solely": ("only", "Shorter adverb."),
    "specified": ("given", "Simpler."),
    "state-of-the-art": ("latest", "Marketing jargon."),
    "strategize": ("plan", "Business jargon — use the simple verb."),
    "submission": ("entry", "Or 'application' / 'form' depending on context."),
    "submit": ("send", "For forms — use the direct verb."),
    "subsequent to": ("after", "Two words to one."),
    "substantial": ("large", "A simpler measurement word."),
    "sufficient": ("enough", "The word people use in speech."),
    "supplement": ("add to", "Phrasal verb."),
    "terminate": ("end", "Direct."),
    "the majority of": ("most", "Two words replace four."),
    "the reason for": ("why", "Simpler question word."),
    "the use of": ("using", "Active form."),
    "thereafter": ("after that", "Two words that are clearer."),
    "therein": ("in that", "Legal archaism."),
    "thereof": ("of that", "Legal archaism."),
    "to the extent that": ("if", "Conditional."),
    "transmit": ("send", "The common word."),
    "unalterable": ("fixed", "Less abstract."),
    "undertake": ("do", "Direct verb."),
    "unilateral": ("one-sided", "Plain explanation built into the word."),
    "utilization": ("use", "Noun form of 'utilize' — also replace with 'use'."),
    "utilize": ("use", "The classic plain-language substitution."),
    "validate": ("confirm", "A common word."),
    "viable": ("workable", "A more concrete adjective."),
    "within the framework of": ("under", "Cut filler."),
    "with respect to": ("about", "Simpler."),
    "with the exception of": ("except", "Four words to one."),
    "witnessed": ("saw", "Simple past tense."),

    # --- Medical / health jargon ---
    "adverse event": ("side effect", "The term patients understand."),
    "ambulate": ("walk", "Medical jargon — use everyday language."),
    "analgesic": ("painkiller", "Plain term for a common medicine type."),
    "benign": ("not cancerous", "Explain, don't just label."),
    "cardiac": ("heart", "Use the organ name, not the adjective."),
    "chronic": ("long-term", "Explain the duration concept."),
    "contraindicated": ("not recommended", "A common medical term that confuses patients."),
    "contusion": ("bruise", "The everyday word."),
    "dermatological": ("skin", "Use the body part name."),
    "dosage": ("dose", "Shorter."),
    "dyspnea": ("shortness of breath", "Explain the symptom."),
    "edema": ("swelling", "The plain description."),
    "etiology": ("cause", "Medical term for origin of disease."),
    "fatality": ("death", "Direct language about serious outcomes."),
    "gastrointestinal": ("stomach and bowel", "Explain the body system."),
    "hematoma": ("bruise", "Or 'collection of blood under the skin' for precision."),
    "hemorrhage": ("heavy bleeding", "Explain the severity."),
    "hypertension": ("high blood pressure", "The term patients know."),
    "hypotension": ("low blood pressure", "Analogous to hypertension explanation."),
    "idiopathic": ("unknown cause", "Explain the meaning."),
    "indication": ("reason to use", "For medications — explain the concept."),
    "laceration": ("cut", "The simpler word."),
    "lesion": ("sore", "Or 'damaged area' — be specific."),
    "malignancy": ("cancer", "Use the word patients understand."),
    "morbidity": ("illness", "Or 'rate of disease' — explain context."),
    "mortality": ("death", "Or 'death rate' — be direct."),
    "myocardial infarction": ("heart attack", "The common term."),
    "neoplasm": ("tumor", "A simpler medical term."),
    "ophthalmic": ("eye", "Use the body part name."),
    "oral": ("by mouth", "Explain the route."),
    "palliative": ("comfort care", "Explain the purpose."),
    "pharmaceutical": ("medicine", "The everyday word."),
    "prognosis": ("outlook", "The concept in plain language."),
    "prophylaxis": ("prevention", "Explain the purpose."),
    "pulmonary": ("lung", "Use the organ name."),
    "regimen": ("plan", "Or 'treatment plan' — be specific."),
    "renal": ("kidney", "Use the organ name."),
    "resection": ("removal", "Surgical term — explain the action."),
    "symptomatology": ("symptoms", "The '-ology' is unnecessary."),
    "therapeutic": ("treatment", "Use the noun people know."),
    "thrombosis": ("blood clot", "Explain the condition."),
    "topical": ("on the skin", "Explain the route."),
    "trauma": ("injury", "The everyday word for physical trauma."),

    # --- Legal / contractual terms ---
    "ab initio": ("from the start", "Latin phrase — translate to English."),
    "ad damnum": ("amount of claim", "Latin legal term."),
    "amended complaint": ("updated claim", "Explain the legal document."),
    "amicus curiae": ("friend of the court", "Explain the role."),
    "bequeath": ("leave", "For wills — use the simpler verb."),
    "bona fide": ("genuine", "Latin — use English."),
    "caveat emptor": ("buyer beware", "Explain the principle."),
    "certiorari": ("review", "Highly technical — explain the action."),
    "codify": ("put into law", "Explain the legislative action."),
    "collateral estoppel": ("issue preclusion", "Explain the doctrine — but this needs a full sentence."),
    "constructive notice": ("should have known", "Explain the legal fiction."),
    "de facto": ("in practice", "Latin phrase with a plain equivalent."),
    "de jure": ("by law", "Contrast with de facto."),
    "decree nisi": ("provisional order", "Family law term."),
    "demurrer": ("challenge to claim", "Explain the legal action."),
    "deposition": ("sworn testimony", "Explain the process."),
    "dispositive": ("deciding the case", "Explain the legal effect."),
    "ejusdem generis": ("of the same kind", "Latin interpretive rule."),
    "encumbrance": ("claim against property", "Explain the property law concept."),
    "enjoin": ("order to stop", "Explain the court action."),
    "estoppel": ("barred from denying", "Complex doctrine — explain in context."),
    "et al.": ("and others", "Abbreviation — spell out or use English."),
    "ex parte": ("from one side", "Explain the procedural situation."),
    "executory": ("not yet performed", "Contract term."),
    "force majeure": ("uncontrollable event", "French legal term — translate."),
    "garnishment": ("wage deduction", "Explain the practical effect."),
    "gravamen": ("main complaint", "Obscure legal term."),
    "guardian ad litem": ("court-appointed representative", "Explain the role."),
    "habeas corpus": ("challenge to detention", "Explain the right."),
    "in camera": ("in private", "Latin — use English."),
    "in forma pauperis": ("without paying fees", "Explain the status."),
    "in rem": ("against the property", "Explain the type of legal action."),
    "indemnify": ("cover losses", "Explain the obligation."),
    "inter alia": ("among other things", "Latin — use English."),
    "interlocutory": ("temporary", "Explain the nature of the order."),
    "intestate": ("without a will", "Explain the situation."),
    "ipso facto": ("by that fact", "Latin — use English."),
    "laches": ("unreasonable delay", "Explain the equitable doctrine."),
    "litigant": ("party to a case", "Use more specific terms when possible."),
    "malfeasance": ("wrongdoing", "A simpler abstraction."),
    "mens rea": ("guilty mind", "Criminal law concept."),
    "meritorious": ("has legal merit", "Explain the evaluation."),
    "moot": ("no longer an issue", "Explain the procedural status."),
    "nunc pro tunc": ("now for then", "Latin procedural term — explain."),
    "pari passu": ("equally", "Latin financial/legal term."),
    "pendente lite": ("while the case is ongoing", "Latin — translate."),
    "per curiam": ("by the court", "Explain the authorship."),
    "per stirpes": ("by branch of family", "Inheritance term — explain."),
    "plenary": ("full", "A simpler word for complete authority."),
    "prayer for relief": ("what is being asked for", "Explain the legal document section."),
    "precedent": ("previous ruling", "Explain the legal concept."),
    "prima facie": ("at first look", "Latin — translate."),
    "pro bono": ("free legal help", "Explain the nature of the service."),
    "pro se": ("representing yourself", "Explain the status."),
    "probative": ("tends to prove", "Evidence term."),
    "quash": ("overturn", "Explain the court action."),
    "quantum meruit": ("reasonable value", "Explain the restitution concept."),
    "quid pro quo": ("something for something", "Latin — translate."),
    "recidivism": ("re-offending", "Criminal justice term."),
    "rescind": ("cancel", "Contract term — use the simpler verb."),
    "respondeat superior": ("employer liability", "Explain the doctrine."),
    "restitution": ("giving back", "Explain the remedy."),
    "scienter": ("knowledge of wrongdoing", "Explain the mental state."),
    "scintilla": ("trace", "A tiny amount — use plain English."),
    "specific performance": ("court order to fulfill contract", "Explain the remedy."),
    "stare decisis": ("following precedent", "Explain the doctrine."),
    "statute": ("law", "The simpler term."),
    "subpoena": ("order to appear", "Explain the document."),
    "subrogation": ("stepping into another's shoes", "Insurance/legal concept — needs explanation."),
    "supersedeas": ("order to pause", "Explain the procedural effect."),
    "testator": ("will-maker", "A descriptive term."),
    "tort": ("civil wrong", "Explain the area of law."),
    "tortfeasor": ("wrongdoer", "A simpler term."),
    "ultra vires": ("beyond authority", "Latin — translate."),
    "vel non": ("or not", "Latin — use English."),
    "vendee": ("buyer", "Legal label — use the role name."),
    "vendor": ("seller", "Legal label — use the role name."),
    "venue": ("location of court", "Explain the procedural concept."),
    "voir dire": ("jury selection", "Explain the process."),
    "writ of certiorari": ("request for review", "Explain the Supreme Court process."),
    "writ of mandamus": ("order to act", "Explain the court order."),

    # --- Financial / business jargon ---
    "accrual": ("buildup", "Explain as 'amount built up over time'."),
    "amortization": ("spreading out cost", "Explain the accounting concept."),
    "arbitrage": ("price difference trading", "Explain the strategy."),
    "asset class": ("type of investment", "Explain the category."),
    "basis point": ("0.01 percentage point", "Give the numerical equivalent."),
    "capital appreciation": ("growth in value", "Explain what happens."),
    "collateralized": ("backed by assets", "Explain the security structure."),
    "commodity": ("raw material", "A simpler term."),
    "debenture": ("unsecured loan", "Explain the financial instrument."),
    "depreciation": ("loss of value over time", "Explain the accounting concept."),
    "derivative": ("contract based on another asset", "Explain the financial product."),
    "diversification": ("spreading risk", "Explain the strategy."),
    "dividend": ("share of profits", "Explain what it is."),
    "equity": ("ownership share", "Explain the concept."),
    "escrow": ("funds held by a third party", "Explain the arrangement."),
    "fiduciary": ("acting in your interest", "Explain the duty."),
    "fiscal year": ("financial year", "The plainer term."),
    "foreclosure": ("lender taking property", "Explain the process."),
    "hedge": ("risk reduction", "Explain the strategy."),
    "illiquid": ("hard to sell quickly", "Explain the property."),
    "leverage": ("borrowed money", "The simpler concept."),
    "lien": ("claim on property", "Explain the legal right."),
    "liquidity": ("how easily an asset sells", "Explain the concept."),
    "maturity": ("end date", "For bonds — explain what happens."),
    "pecuniary": ("financial", "A simpler adjective."),
    "portfolio": ("collection of investments", "Explain the composition."),
    "principal": ("original amount", "Distinguish from interest."),
    "prospectus": ("investment details document", "Explain the document."),
    "recession": ("economic downturn", "Explain in plain terms."),
    "securities": ("stocks and bonds", "Use specific terms."),
    "securitization": ("bundling loans", "Explain the financial engineering."),
    "solvency": ("ability to pay debts", "Explain the financial condition."),
    "underwriter": ("risk assessor", "Explain the role."),
    "volatility": ("price swings", "Explain the market behavior."),
    "yield": ("return", "A simpler term for investment income."),

    # --- Technology / computing jargon ---
    "authentication": ("proving identity", "Explain the security process."),
    "bandwidth": ("capacity", "A simpler concept word."),
    "cache": ("temporary storage", "Explain the function."),
    "deprecated": ("outdated", "Explain the status."),
    "encryption": ("scrambling data", "Explain the security function."),
    "implementation": ("setup", "A more concrete term."),
    "initialize": ("start up", "Phrasal verb."),
    "latency": ("delay", "The plain concept."),
    "middleware": ("connecting software", "Explain the architectural role."),
    "protocol": ("set of rules", "For communication — explain the concept."),
    "redundancy": ("backup", "Explain the purpose."),
    "repository": ("storage location", "A plainer description."),
    "scalability": ("ability to grow", "Explain the property."),
    "throughput": ("processing speed", "Explain the measure."),

    # --- Academic / research jargon ---
    "epistemology": ("theory of knowledge", "Philosophy term — needs explanation."),
    "heuristic": ("rule of thumb", "The everyday equivalent."),
    "ontology": ("classification system", "Or 'study of what exists' — explain context."),
    "paradigm": ("model", "Or 'framework' — a simpler word."),
    "pedagogy": ("teaching method", "Explain the concept."),
    "qualitative": ("descriptive", "Explain the research type."),
    "quantitative": ("numerical", "Explain the research type."),
    "taxonomy": ("classification", "A simpler word."),
    "teleological": ("purpose-driven", "Explain the philosophical concept."),

    # --- Nominalizations (nouns that hide verbs) ---
    "conduct an analysis of": ("analyze", "Hidden verb — use the verb directly."),
    "conduct an assessment of": ("assess", "Hidden verb."),
    "conduct an evaluation of": ("evaluate", "Hidden verb."),
    "conduct an examination of": ("examine", "Hidden verb."),
    "conduct an investigation of": ("investigate", "Hidden verb."),
    "conduct a review of": ("review", "Hidden verb."),
    "give consideration to": ("consider", "Hidden verb."),
    "give recognition to": ("recognize", "Hidden verb."),
    "have a discussion about": ("discuss", "Hidden verb."),
    "have a need for": ("need", "Hidden verb."),
    "hold a meeting about": ("meet about", "Hidden verb."),
    "is applicable to": ("applies to", "Remove empty verb."),
    "is dependent on": ("depends on", "Remove empty verb."),
    "is indicative of": ("indicates", "Remove empty verb."),
    "is reflective of": ("reflects", "Remove empty verb."),
    "make a decision about": ("decide", "Hidden verb."),
    "make a distinction between": ("distinguish", "Hidden verb."),
    "make a judgement about": ("judge", "Hidden verb."),
    "make a recommendation": ("recommend", "Hidden verb."),
    "make a statement about": ("state", "Hidden verb."),
    "make an adjustment to": ("adjust", "Hidden verb."),
    "make an agreement": ("agree", "Hidden verb."),
    "make an announcement": ("announce", "Hidden verb."),
    "make an argument for": ("argue for", "Hidden verb."),
    "make an arrangement": ("arrange", "Hidden verb."),
    "make an assumption": ("assume", "Hidden verb."),
    "make an attempt": ("attempt", "Hidden verb — or even 'try'."),
    "make an enquiry": ("ask", "Hidden verb."),
    "make preparations for": ("prepare for", "Hidden verb."),
    "make provision for": ("provide for", "Hidden verb."),
    "place emphasis on": ("emphasize", "Hidden verb."),
    "provide a description of": ("describe", "Hidden verb."),
    "provide an explanation of": ("explain", "Hidden verb."),
    "take action on": ("act on", "Hidden verb."),
    "take into consideration": ("consider", "Hidden verb."),
    "undertake a study of": ("study", "Hidden verb."),
}

# Additional single-word complex-to-simple mappings that don't need explanations
SIMPLE_WORD_MAP: dict[str, str] = {
    "accomplish": "do",
    "accordingly": "so",
    "accrue": "build up",
    "acquiesce": "agree",
    "acquire": "get",
    "administer": "manage",
    "advise": "tell",
    "aggregate": "total",
    "alleviate": "reduce",
    "allocate": "give",
    "anticipate": "expect",
    "append": "add",
    "apprise": "tell",
    "appropriate": "proper",
    "approximately": "about",
    "articulate": "say",
    "assistance": "help",
    "attain": "meet",
    "beneficial": "helpful",
    "capability": "ability",
    "category": "group",
    "cognizant": "aware",
    "collaborate": "work with",
    "commensurate": "matching",
    "compensate": "pay",
    "compliant": "follows rules",
    "component": "part",
    "concur": "agree",
    "configuration": "setup",
    "consequently": "so",
    "consolidate": "combine",
    "consummate": "finish",
    "contemplate": "think about",
    "convene": "meet",
    "deem": "consider",
    "deficient": "lacking",
    "demonstrate": "show",
    "designate": "name",
    "detrimental": "harmful",
    "disburse": "pay out",
    "discontinue": "stop",
    "disseminate": "spread",
    "domicile": "home",
    "duration": "length",
    "effectiveness": "how well it works",
    "elect": "choose",
    "eligible": "allowed",
    "empower": "allow",
    "endeavour": "try",
    "enumerate": "list",
    "erroneous": "wrong",
    "establish": "prove",
    "exacerbate": "worsen",
    "exclude": "leave out",
    "exclusively": "only",
    "expedite": "speed up",
    "expenditure": "spending",
    "facilitate": "help",
    "feasible": "workable",
    "formulate": "create",
    "functionality": "feature",
    "henceforth": "from now on",
    "hereinafter": "later in this document",
    "identical": "same",
    "illuminate": "explain",
    "immediately": "at once",
    "impair": "harm",
    "imperative": "essential",
    "implement": "start using",
    "imply": "suggest",
    "inception": "start",
    "incorporate": "include",
    "incumbent upon": "required of",
    "indemnify": "cover loss",
    "indicate": "show",
    "ineffective": "not working",
    "inordinate": "excessive",
    "interface": "connect",
    "intervene": "step in",
    "intimate": "hint",
    "jeopardize": "risk",
    "jurisdiction": "authority",
    "leverage": "use",
    "magnitude": "size",
    "mandate": "order",
    "manufacture": "make",
    "material": "relevant",
    "mitigate": "reduce",
    "moreover": "also",
    "necessitate": "need",
    "negligible": "tiny",
    "negotiate": "discuss",
    "notify": "tell",
    "numerous": "many",
    "objective": "goal",
    "obligation": "duty",
    "obsolete": "outdated",
    "optimum": "best",
    "originate": "start",
    "parameters": "limits",
    "permissible": "allowed",
    "perpetrate": "commit",
    "perpetuate": "continue",
    "pertain": "relate to",
    "possess": "have",
    "predominantly": "mainly",
    "prerequisite": "requirement",
    "prescribe": "require",
    "preserve": "keep",
    "principal": "main",
    "prioritize": "rank",
    "proactive": "acting early",
    "prohibit": "ban",
    "promulgate": "announce",
    "proportion": "share",
    "proposition": "idea",
    "prospective": "future",
    "provisions": "rules",
    "proximity": "nearness",
    "qualify": "meet requirements",
    "reimburse": "pay back",
    "relinquish": "give up",
    "relocate": "move",
    "remittance": "payment",
    "render": "make",
    "replicate": "copy",
    "requisite": "required",
    "rescind": "cancel",
    "resilient": "strong",
    "resolve": "solve",
    "retrospective": "looking back",
    "revision": "change",
    "scrutinize": "examine",
    "signify": "mean",
    "specification": "detail",
    "standardize": "make consistent",
    "stipulate": "require",
    "substantiate": "prove",
    "supplement": "add to",
    "sustain": "support",
    "synthesize": "combine",
    "terminate": "end",
    "trajectory": "path",
    "transcribe": "write down",
    "transform": "change",
    "transitory": "temporary",
    "ubiquitous": "everywhere",
    "unilateral": "one-sided",
    "utilize": "use",
    "validate": "confirm",
    "verify": "check",
    "vicinity": "area",
    "visualize": "imagine",
}
